params:
  env:
    name: UnstableGrasp-v1
#    observation_type: tactile_flatten

  network:
    actor: DiagGaussianActor
    actor_mlp:
      layer_sizes: [64, 64]
      activation: elu
      layernorm: False
    actor_logstd_init: 0

    critic: MLPCritic
    critic_mlp:
      layer_sizes: [64, 64]
      activation: elu
      layernorm: False

  config:
    use_gae: True
    num_env_steps: 50000
    num_steps: 16
    num_processes: 8
    lr: 0.0003
    entropy_coef: 0
    value_loss_coef: 0.5
    ppo_epoch: 10
    num_mini_batch: 32
    gamma: 0.99
    gae_lambda: 0.95
    use_linear_lr_decay: True
    use_proper_time_limits: True
    norm_reward: True
    norm_obs: True
    clip_reward: 10.
    clip_obs: 10.
    clip_param: 0.2
    max_grad_norm: 0.5